config/routes.rb
ConnectedIn::Application.routes.draw do
  get '/people/' => "people#show_all", as: "show_all"

  get '/people/Michael_Jordan' => "people#show_mike", as: "mike"
  get '/people/Seth_Godin' => "people#show_seth", as: "seth"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  def show_all

  end

  def show_mike

  end 

  def show_seth

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ConnectedIn</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/people/show_all.html.erb
<h1>People who have a lot to teach me!</h1>

<ul>
	<li><%= link_to "Michael Jordan", mike_path%></li>
	<li><%= link_to "Seth Godin", seth_path%></li>
</ul>

app/views/people/show_mike.html.erb
<h1> I wanna be just like Mike</h1>

<iframe width="560" height="315" src="//www.youtube.com/embed/9zSVu76AX3I" frameborder="0" allowfullscreen></iframe>

<br>
<%= link_to "back", show_all_path %>

app/views/people/show_seth.html.erb
<h1>Seth Godin</h1>

<iframe src="http://www.sethgodin.com/sg/" frameborder="0" width="100%" height="500px"></iframe>
<br>
<%= link_to "back", show_all_path %>